spring:
  application:
    name: extension-blocker
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/extension_blocker}
    username: ${DB_USERNAME:hacanna42}
    password: ${DB_PASSWORD:}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: 8080
